language: php

php: 
  - "7.1"
  - "7.2"

env:
  - LARAVEL_VERSION="5.5.*"
  - LARAVEL_VERSION="dev-master"

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: phpunit